# Generated by Django 4.1.5 on 2023-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessHoursTime",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("store_id", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatusTimeStampt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("store_id", models.IntegerField()),
                ("timestamp_utc", models.DateTimeField()),
                ("store_status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimezonesDetails",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("store_id", models.IntegerField()),
                ("timezone_str", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
